
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: portfolio-app:latest
    container_name: portfolio-app
    restart: unless-stopped
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dokploy-network:
    external: true
